# Use postgres/example user/password credentials
version: '3'

services:
  auth:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - GIN_MODE=release
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
